{application,web_dev_utils,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,file_system]},
              {description,"Library to enable awesome local development for websites and web applications"},
              {modules,['Elixir.WebDevUtils','Elixir.WebDevUtils.Assets',
                        'Elixir.WebDevUtils.CodeReloader',
                        'Elixir.WebDevUtils.Components',
                        'Elixir.WebDevUtils.FileSystem',
                        'Elixir.WebDevUtils.LiveReload']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
